### PR TITLE
Configure github actions for CI

### PR DESCRIPTION
**Pull request by bpinto**
There is no better way other than this to start working on this repository, right? 😀

### CODE REVIEW

**Comment by bpinto** [comment]
@mAAdhaTTah I intend to start with this repository, what do you think? I was thinking after we get all PRs (dependabot) merged on kefir-test-utils we could maybe release a new major there so that I can use it here?

**Comment by bpinto** [comment]
@mAAdhaTTah now that our work on kefir-test-utils is complete (we still need a version release there but that can happen later), what do you think about this?

I'd like to start updating all the old libraries after this. Is there a feature you would like to be added to this project?

**Comment by mAAdhaTTah** [comment]
I don't think there are any new features or breaking changes required for this major bump. There is a request for a new matcher in #86 but the OP didn't respond and I don't want to add API surface area without a clear use case, plus it's not breaking, so we don't need it for this major version bump.

**Review by mAAdhaTTah — APPROVED** [review]

**Comment by bpinto** [comment]
What do we do with stale issues? Do we close them?

**Comment by mAAdhaTTah** [comment]
Yeah, I usually do, but I haven't been maintaining these test utils as actively lately so leaving it open wasn't a big deal.

**Pull request merged**
